#pragma once
#ifndef EN_H
#define S_1 "WELCOME TO GENSHIN IMPACT WISH SIMULATOR CLI V2.4.2"
#define S_2 "by Jirehlov Research"
#define S_3 "Source code available on GitHub: Jirehlov_Genshin-Impact-Wish-Simulator-CLI"
#define S_4 "GPL-3.0 License"
#define S_5 "Choose Your Wishes (Banners):"
#define S_6 "-1: Quit;"
#define S_7 "1: Character Event Wish;"
#define S_8 "3: Weapon Event Wish;"
#define S_9 "4: Permanent Wish;"
#define S_10 "5: Novice Wish;"
#define S_11 "Character(s) cannot be read!"
#define S_12 "Choose Your Events:"
#define S_13 "-1: Re-choose Wishes (Banners) (Records will be reset!)"
#define S_14 "1: Ballad in Goblets_20200928-20201018 (Venti, Barbara, Fischl, Xiangling)"
#define S_15 "2: Sparkling Steps_20201020-20201110 (Klee, Xingqiu, Noelle, Sucrose)"
#define S_16 "3: Farewell of Snezhnaya_20201111-20201201 (Tartaglia, Diona, Beidou, Ningguang)"
#define S_17 "4: Gentry of Hermitage_20201201-20201222 (Zhongli, Xinyan, Razor, Chongyun)"
#define S_18 "5: Secretum Secretorum_20201223-20210112 (Albedo, Fischl, Sucrose, Bennett)"
#define S_19 "6: Adrift in the Harbor_20210112-20210202 (Ganyu, Xiangling, Xingqiu, Noelle)"
#define S_20 "7: Invitation to Mundane Life_20210203-20210217 (Xiao, Diona, Beidou, Xinyan)"
#define S_21 "8: Dance of Lanterns_20210217-20210302 (Keqing, Ningguang, Bennett, Barbara)"
#define S_22 "9: Moment of Bloom_20210302-20210316 (Hu Tao, Xingqiu, Xiangling, Chongyun)"
#define S_23 "10: Ballad in Goblets_20210317-20210406 (Venti, Sucrose, Razor, Noelle)"
#define S_24 "11: Farewell of Snezhnaya_20210406-20210427 (Tartaglia, Rosaria, Barbara, Fischl)"
#define S_25 "12: Gentry of Hermitage_20210428-20210518 (Zhongli, Yanfei, Noelle, Diona)"
#define S_26 "13: Born of Ocean Swell_20210518-20210608 (Eula, Xinyan, Xingqiu, Beidou)"
#define S_27 "14: Sparkling Steps_20210609-20210629 (Klee, Sucrose, Fischl, Barbara)"
#define S_28 "15: Leaves in the Wind_20210629-20210720 (Kaedehara Kazuha, Rosaria, Bennett, Razor)"
#define S_29 "16: The Heron's Court_20210721-20210810 (Kamisato Ayaka, Yanfei, Ningguang, Chongyun)"
#define S_30 "17: Tapestry of Golden Flames_20210810-20210831 (Yoimiya, Sayu, Diona, Xinyan)"
#define S_31 "Invalid event!"
#define S_32 "1: Epitome Invocation_20200928-20201018 (Aquila Favonia, Amos' Bow, The Flute, The Bell, The Widsith, The Stringless, Favonius Lance)"
#define S_33 "2: Epitome Invocation_20201020-20201109 (Lost Prayer to the Sacred Winds, Wolf's Gravestone, Sacrificial Sword, Sacrificial Bow, Sacrificial Greatsword, Sacrificial Fragments, Dragon's Bane)"
#define S_34 "3: Epitome Invocation_20201111-20201201 (Memory of Dust, Skyward Harp, Rainslasher, Eye of Perception, Rust, Favonius Lance, The Flute)"
#define S_35 "4: Epitome Invocation_20201201-20201222 (Vortex Vanquisher, The Unforged, Lion's Roar, The Bell, Favonius Codex, Favonius Warbow, Dragon's Bane)"
#define S_36 "5: Epitome Invocation_20201223-20210112 (Summit Shaper, Skyward Atlas, Favonius Sword, Favonius Greatsword, Favonius Lance, Sacrificial Fragments, The Stringless)"
#define S_37 "6: Epitome Invocation_20210112-20210202 (Skyward Pride, Amos' Bow, Sacrificial Sword, The Bell, Dragon's Bane, Eye of Perception, Favonius Warbow)"
#define S_38 "7: Epitome Invocation_20210203-20210223 (Primordial Jade Cutter, Primordial Jade Winged-Spear, Rust, Eye of Perception, Favonius Lance, Sacrificial Greatsword, The Flute)"
#define S_39 "8: Epitome Invocation_20210223-20210316 (Staff of Homa, Wolf's Gravestone, Lithic Blade, Lithic Spear, Sacrificial Bow, The Widsith, Lion's Roar)"
#define S_40 "9: Epitome Invocation_20210317-20210406 (Elegy for the End, Skyward Blade, The Alley Flash, Wine and Song, Favonius Greatsword, Favonius Warbow, Dragon's Bane)"
#define S_41 "10: Epitome Invocation_20210406-20210427 (Skyward Harp, Lost Prayer to the Sacred Winds, Alley Hunter, Favonius Sword, Sacrificial Greatsword, Favonius Codex, Favonius Lance)"
#define S_42 "11: Epitome Invocation_20210428-20210518 (Summit Shaper, Memory of Dust, The Flute, Lithic Blade, Lithic Spear, Eye of Perception, Sacrificial Bow)"
#define S_43 "12: Epitome Invocation_20210518-20210608 (Song of Broken Pines, Aquila Favonia, Sacrificial Sword, Rainslasher, Dragon's Bane, Sacrificial Fragments, Rust)"
#define S_44 "13: Epitome Invocation_20210609-20210629 (Skyward Pride, Lost Prayer to the Sacred Winds, Mitternachts Waltz, Lion's Roar, The Bell, Favonius Lance, The Widsith)"
#define S_45 "14: Epitome Invocation_20210629-20210720 (Freedom-Sworn, Skyward Atlas, The Alley Flash, Wine and Song, Alley Hunter, Favonius Greatsword, Dragon's Bane)"
#define S_46 "15: Epitome Invocation_20210721-20210810 (Mistsplitter Reforged, Skyward Spine, The Stringless, Favonius Sword, Favonius Lance, Favonius Codex, Sacrificial Greatsword)"
#define S_47 "16: Epitome Invocation_20210810-20210831 (Thundering Pulse, Skyward Blade, Favonius Warbow, Sacrificial Sword, Dragon's Bane, Rainslasher, Sacrificial Fragments)"
#define S_48 "1: Wanderlust Invocation_20200928-20201222 (Released)"
#define S_49 "2: Wanderlust Invocation_20201223-20210427 (Adds Diona and Xinyan)"
#define S_50 "3: Wanderlust Invocation_20210428-20210608 (Adds Rosaria)"
#define S_51 "4: Wanderlust Invocation_20210609-20210831 (Adds Yanfei)"
#define S_52 "1: Beginners' wish"
#define S_53 "Invalid banner!"
#define S_54 "How many wishes?"
#define S_55 "-1: Re-choose Events;"
#define S_56 "1: 1 Wish;"
#define S_57 "10: 10 Wishes;"
#define S_58 "-2: Show Luckiest 10 Pulls (a succession of);"
#define S_59 "-3: Reset records;"
#define S_60 "-4: Print or not"
#define S_61 "-6: Epitomized Path"
#define S_62 "Default"
#define S_63 "Luckiness: "
#define S_64 "Record has been reset!"
#define S_65 "Printing disabled!"
#define S_66 "Printing enabled!"
#define S_67 "Epitomized Path?"
#define S_68 "-1: Return;"
#define S_69 "1: The first weapon in order;"
#define S_70 "2: The second weapon in order;"
#define S_71 "0: Cancel and Reset"
#define S_72 "Incorrect input!"
#define S_73 "In total, You have pulled "
#define S_74 " wishes."
#define S_75 "5-stars:   "
#define S_76 "4-stars:   " 
#define S_77 "5-star-characters : 5-star-weapons : 4-star-characters : 4-star-weapons   "
#define S_78 "max 5-star pity:   "
#define S_79 " initially at "
#define S_80 "-th non-5-star  "
#define S_81 "-th wishes"
#define S_82 "min 5-star pity:   "
#define S_83 "ave 5-star pity:   "
#define S_84 " seconds elapsed."
#define S_85 "You get:"
#define S_86 "Started at:  "
#define S_87 "Ended at:  "
#define S_88 "4-stars Distribution"
#define S_89 "5-stars Distribution"
#define S_90 "-5: Pity Distribution"
#define S_91 "confirm resttting records?"
#define S_92 "-1: cancel and return"
#define S_93 "1: reset"
#define S_94 "18: Reign of Serenity_20210901-20210921 (Raiden Shogun, Kujo Sara, Xiangling, Sucrose)"
#define S_95 "19: Drifting Luminescence_20210921-20211012 (Sangonomiya Kokomi, Rosaria, Beidou, Xingqiu)"
#define S_96 "17: Epitome Invocation_20210901-20210921 (Engulfing Lightning, The Unforged, Sacrificial Bow, Lion's Roar, The Widsith, Favonius Lance, The Bell)"
#define S_97 "18: Epitome Invocation_20210921-20211012 (Everlasting Moonglow, Primordial Jade Cutter, The Flute, Favonius Greatsword, Dragon's Bane, Favonius Codex, The Stringless)"
#define S_98 "5: Wanderlust Invocation_20210901-20211012 (Adds Sayu)"
#define S_99 "6: Wanderlust Invocation_20211013-20211123 (Adds Kujo Sara)"
#define S_100 "20: Farewell of Snezhnaya_20211013-20211102 (Tartaglia, Ningguang, Chongyun, Yanfei)"
#define S_101 "21: Moment of Bloom_20211102-20211123 (Hu Tao, Thoma, Diona, Sayu)"
#define S_102 "22: Secretum Secretorum_20211124-20211214 (Albedo, Rosaria, Noelle, Bennett)"
#define S_103 "23: Oni's Royale_20211214-20220104 (Arataki Itto, Gorou, Xiangling, Barbara)"
#define S_104 "19: Epitome Invocation_20211013-20211102 (Polar Star, Memory of Dust, Akuoumaru, Favonius Sword, Favonius Lance, Eye of Perception, Rust)"
#define S_105 "20: Epitome Invocation_20211102-20211123 (Staff of Homa, Elegy for the End, Wavebreaker's Fin, Mouun's Moon, Sacrificial Sword, Rainslasher, The Widsith)"
#define S_106 "7: Wanderlust Invocation_20211124-20220104 (Adds Thoma)"
#define S_107 "1: Born of Ocean Swell_20211124-20211214 (Eula, Rosaria, Noelle, Bennett)"
#define S_108 "2: Character Event Wish-2;"
#define S_109 "-2: Re-choose Wishes (Banners) (Records will NOT be reset!)"
#define S_110 "8: Wanderlust Invocation_20220105-20220215 (Adds Gorou)"
#define S_111 "21: Epitome Invocation_20211124-20211214 (Freedom Sworn, Song of Broken Pines, Alley Hunter, Lion's Roar, Dragon's Bane, Wine and Song, Sacrificial Greatsword)"
#define S_112 "-127: Return some non-array variables"
#define S_113 "-63: Specific Output Mode;"
#define S_114 "Specific Item (No.)"
#define S_115 "How many of this item ("
#define S_116 "-1: Quit specific-ing and execute;"
#define S_117 "UP 5-star"
#define S_118 "non-UP 5-star"
#define S_119 "UP 4-star"
#define S_120 "non-UP 4-star"
#define S_121 "3-star"
#define S_122 "Invalid item"
#define S_123 "-2: Quit specific-ing and give up;"
#define S_124 ") ?"
#define S_125 "You didn't made any specific-ing!"
#define S_126 "22: Epitome Invocation_20211214-20210104 (Redhorn Stonethresher, Skyward Harp, The Alley Flash, Mitternachts Waltz, Favonius Lance, Sacrificial Fragments, The Bell)"
#define S_127 "This go, You have pulled "
#define S_128 "-31: Set pity profile"
#define S_129 "Should the next 5-star guaranteed to be up-ped? 1: Yes; 0: No"
#define S_130 "How many pulls are you away from the last 5-star？"
#define S_131 "Should the next 4-star guaranteed to be up-ped? 1: Yes; 0: No"
#define S_132 "How many pulls are you away from the last 4-star？"
#define S_133 "How many pulls are you away from the last 5-star character？"
#define S_134 "How many pulls are you away from the last 5-star weapon？"
#define S_135 "How many pulls are you away from the last 4-star character？"
#define S_136 "How many pulls are you away from the last 4-star weapon？"
#define S_137 " (count from 0)"
#define S_138 "-1: quit (not save)"
#define S_139 "-2: quit (save)"
#define S_140 "fate points? (0, 1 or 2)"
#define S_141 "Checking profile validity..."
#define S_142 "Checking profile passed!"
#define S_143 "Checking profile failed! Changes undone!"
#define S_144 "24: The Transcendent One Returns_20220105-20220125 (Shenhe, Yun Jin, Ningguang, Chongyun)"
#define S_145 "25: Gentry of Hermitage_20220125-20220215 (Zhongli, Yanfei, Xingqiu, Beidou)"
#define S_146 "2: Invitation to Mundane Life_20220105-20220125 (Xiao, Yun Jin, Ningguang, Chongyun)"
#define S_147 "3: Adrift in the Harbor_20220125-20220215 (Ganyu, Yanfei, Xingqiu, Beidou)"
#define S_148 "23: Epitome Invocation_20220105-20220125 (Calamity Queller, Primordial Jade Winged-Spear, Lithic Spear, The Flute, Favonius Warbow, The Widsith, Favonius Greatsword)"
#define S_149 "24: Epitome Invocation_20220125-20220215 (Vortex Vanquisher, Amos' Bow, Lithic Blade, Favonius Sword, Dragon's Bane, Favonius Codex, Sacrificial Bow)"
#define S_150 "9: Wanderlust Invocation_20220216- (Adds Yun Jin)"
#define C_0 "\"Driving Thunder\" Keqing (Electro)"
#define C_1 "\"Astral Reflection\" Mona (Hydro)"
#define C_2 "\"Icy Resurrection\" Qiqi (Cryo)"
#define C_3 "\"The Dark Side of Dawn\" Diluc (Pyro)"
#define C_4 "\"Dandelion Knight\" Jean (Anemo)"
#define C_5 "Amos' Bow (Bow)"
#define C_6 "Skyward Harp (Bow)"
#define C_7 "Lost Prayer to the Sacred Winds (Catalyst)"
#define C_8 "Skyward Atlas (Catalyst)"
#define C_9 "Primordial Jade Winged-Spear (Polearm)"
#define C_10 "Skyward Spine (Polearm)"
#define C_11 "Wolf's Gravestone (Claymore)"
#define C_12 "Skyward Pride (Claymore)"
#define C_13 "Skyward Blade (Sword)"
#define C_14 "Aquila Favonia (Sword)"
#define C_15 "\"Thorny Benevolence\" Rosaria (Cryo)"
#define C_16 "\"Blazing Riff\" Xinyan (Pyro)"
#define C_17 "\"Harmless Sweetie\" Sucrose (Anemo)"
#define C_18 "\"Kätzlein Cocktail\" Diona (Cryo)"
#define C_19 "\"Frozen Ardor\" Chongyun (Cryo)"
#define C_20 "\"Chivalric Blossom\" Noelle (Geo)"
#define C_21 "\"Trial by Fire\" Bennett (Pyro)"
#define C_22 "\"Prinzessin der Verurteilung!\" Fischl (Electro)"
#define C_23 "\"Eclipsing Star\" Ningguang (Geo)"
#define C_24 "\"Juvenile Galant\" Xingqiu (Hydro)"
#define C_25 "\"Uncrowned Lord of the Ocean\" Beidou (Electro)"
#define C_26 "\"Exquisite Delicacy\" Xiangling (Pryo)"
#define C_27 "\"Gliding Champion\" Amber (Pryo)"
#define C_28 "\"Wolf Boy\" Razor (Electro)"
#define C_29 "\"Frostwind Swordsman\" Kaeya (Cryo)"
#define C_30 "\"Shining Idol\" Barbara (Hydro)"
#define C_31 "\"Witch of Purple Rose\" Lisa (Electro)"
#define C_32 "Rust (Bow)"
#define C_33 "Sacrificial Bow (Bow)"
#define C_34 "The Stringless (Bow)"
#define C_35 "Favonius Warbow (Bow)"
#define C_36 "Eye of Perception (Catalyst)"
#define C_37 "Sacrificial Fragments (Catalyst)"
#define C_38 "The Widsith (Catalyst)"
#define C_39 "Favonius Codex (Catalyst)"
#define C_40 "Favonius Lance (Polearm)"
#define C_41 "Dragon's Bane (Polearm)"
#define C_42 "Rainslasher (Claymore)"
#define C_43 "Sacrificial Greatsword (Claymore)"
#define C_44 "The Bell (Claymore)"
#define C_45 "Favonius Greatsword (Claymore)"
#define C_46 "Lion's Roar (Sword)"
#define C_47 "Sacrificial Sword (Sword)"
#define C_48 "The Flute (Sword)"
#define C_49 "Favonius Sword (Sword)"
#define C_50 "Slingshot (Bow)"
#define C_51 "Sharpshooter's Oath (Bow)"
#define C_52 "Raven Bow (Bow)"
#define C_53 "Emerald Orb (Catalyst)"
#define C_54 "Thrilling Tales of Dragon Slayers (Catalyst)"
#define C_55 "Magic Guide (Catalyst)"
#define C_56 "Black Tassel (Polearm)"
#define C_57 "Debate Club (Claymore)"
#define C_58 "Bloodtainted Greatsword (Claymore)"
#define C_59 "Ferrous Shadow (Claymore)"
#define C_60 "Skyrider Sword (Sword)"
#define C_61 "Harbinger of Dawn (Sword)"
#define C_62 "Cool Steel (Sword)"
#define C_63 "\"Windborne Bard\" Venti (Anemo)"
#define C_64 "\"Fleeing Sunlight\" Klee (Pyro)"
#define C_65 "\"Childe\" Tartaglia (Hydro)"
#define C_66 "\"Vago Mundo\" Zhongli (Geo)"
#define C_67 "\"Kreideprinz\" Albedo (Geo)"
#define C_68 "\"Plenilune Gaze\" Ganyu (Cryo)"
#define C_69 "\"Vigilant Yaksha\" Xiao (Anemo)"
#define C_70 "\"Fragrance in Thaw\" Hu Tao (Pryo)"
#define C_71 "\"Wise Innocence\" Yanfei (Pyro)"
#define C_72 "\"Dance of the Shimmering Wave\" Eula (Cryo)"
#define C_73 "Memory of Dust (Catalyst)"
#define C_74 "Vortex Vanquisher (Polearm)"
#define C_75 "The Unforged (Claymore)"
#define C_76 "Summit Shaper (Sword)"
#define C_77 "Primordial Jade Cutter (Sword)"
#define C_78 "Staff of Homa (Polearm)"
#define C_79 "Lithic Blade (Claymore)"
#define C_80 "Lithic Spear (Polearm)"
#define C_81 "Elegy of the End (Bow)"
#define C_82 "The Alley Flash (Sword)"
#define C_83 "Wine and Song (Catalyst)"
#define C_84 "Alley Hunter (Bow)"
#define C_85 "Song of Broken Pines (Claymore)"
#define C_86 "\"Scarlet Leaves Pursue Wild Waves\" Kaedehara Kazuha (Anemo)"
#define C_87 "Freedom-Sworn (Sword)"
#define C_88 "Mitternachts Waltz (Bow)"
#define C_89 "\"Frostflake Heron\" Kamisato Ayaka (Cryo)"
#define C_90 "\"Frolicking Flames\" Yoimiya (Pyro)"
#define C_91 "\"Mujina Ninja\" Sayu (Anemo)"
#define C_92 "Mistsplitter Reforged (Sword)"
#define C_93 "Thundering Pulse (Bow)"
#define C_94 "\"Pearl of Wisdom\" Sangonomiya Kokomi (Hydro)"
#define C_95 "\"Crowfeather Kaburaya\" Kujo Sara (Electro)"
#define C_96 "\"Plane of Euthymia\" Raiden Shogun (Electro)"
#define C_97 "Engulfing Lightning (Polearm)"
#define C_98 "Everlasting Moonglow (Catalyst)"
#define C_99 "Yae Miko (Electro)"
#define C_100 "\"Protector From Afar\" Thoma (Pryo)"
#define C_101 "Polar Star (Bow)"
#define C_102 "Mouun's Moon (Bow)"
#define C_103 "Wavebreaker's Fin (Polearm)"
#define C_104 "Akuoumaru (Claymore)"
#define C_105 "\"Hanamizaka Heroics\" Arataki Itto (Geo)"
#define C_106 "\"Canine Warrior\" Gorou (Geo)"
#define C_107 "Redhorn Stonethresher (Claymore)"
#define C_108 "\"Stage Lucida\" Yun Jin (Geo)"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
#define C_109 "\"Lonesome Transcendence\" Shenhe (Cryo)"
#define C_110 "Calamity Queller (Polearm)"
#define C_111 "Kamisato Ayato (Hydro)"
#define X_0 "Keqing"
#define X_1 "Mona"
#define X_2 "Qiqi"
#define X_3 "Diluc"
#define X_4 "Jean"
#define X_5 "Amos' Bow"
#define X_6 "Skyward Harp"
#define X_7 "Lost Prayer to the Sacred Winds"
#define X_8 "Skyward Atlas"
#define X_9 "Primordial Jade Winged-Spear"
#define X_10 "Skyward Spine"
#define X_11 "Wolf's Gravestone"
#define X_12 "Skyward Pride"
#define X_13 "Skyward Blade"
#define X_14 "Aquila Favonia"
#define X_15 "Rosaria"
#define X_16 "Xinyan"
#define X_17 "Sucrose"
#define X_18 "Diona"
#define X_19 "Chongyun"
#define X_20 "Noelle"
#define X_21 "Bennett"
#define X_22 "Fischl"
#define X_23 "Ningguang"
#define X_24 "Xingqiu"
#define X_25 "Beidou"
#define X_26 "Xiangling"
#define X_27 "Amber"
#define X_28 "Razor"
#define X_29 "Kaeya"
#define X_30 "Barbara"
#define X_31 "Lisa"
#define X_32 "Rust"
#define X_33 "Sacrificial Bow"
#define X_34 "The Stringless"
#define X_35 "Favonius Warbow"
#define X_36 "Eye of Perception"
#define X_37 "Sacrificial Fragments"
#define X_38 "The Widsith"
#define X_39 "Favonius Codex"
#define X_40 "Favonius Lance"
#define X_41 "Dragon's Bane"
#define X_42 "Rainslasher"
#define X_43 "Sacrificial Greatsword"
#define X_44 "The Bell"
#define X_45 "Favonius Greatsword"
#define X_46 "Lion's Roar"
#define X_47 "Sacrificial Sword"
#define X_48 "The Flute"
#define X_49 "Favonius Sword"
#define X_50 "Slingshot"
#define X_51 "Sharpshooter's Oath"
#define X_52 "Raven Bow"
#define X_53 "Emerald Orb"
#define X_54 "Thrilling Tales of Dragon Slayers"
#define X_55 "Magic Guide"
#define X_56 "Black Tassel"
#define X_57 "Debate Club"
#define X_58 "Bloodtainted Greatsword"
#define X_59 "Ferrous Shadow"
#define X_60 "Skyrider Sword"
#define X_61 "Harbinger of Dawn"
#define X_62 "Cool Steel"
#define X_63 "Venti"
#define X_64 "Klee"
#define X_65 "Tartaglia"
#define X_66 "Zhongli"
#define X_67 "Albedo"
#define X_68 "Ganyu"
#define X_69 "Xiao"
#define X_70 "Hu Tao"
#define X_71 "Yanfei"
#define X_72 "Eula"
#define X_73 "Memory of Dust"
#define X_74 "Vortex Vanquisher"
#define X_75 "The Unforged"
#define X_76 "Summit Shaper"
#define X_77 "Primordial Jade Cutter"
#define X_78 "Staff of Homa"
#define X_79 "Lithic Blade"
#define X_80 "Lithic Spear"
#define X_81 "Elegy of the End"
#define X_82 "The Alley Flash"
#define X_83 "Wine and Song"
#define X_84 "Alley Hunter"
#define X_85 "Song of Broken Pines"
#define X_86 "Kaedehara Kazuha"
#define X_87 "Freedom-Sworn"
#define X_88 "Mitternachts Waltz"
#define X_89 "Kamisato Ayaka"
#define X_90 "Yoimiya"
#define X_91 "Sayu"
#define X_92 "Mistsplitter Reforged"
#define X_93 "Thundering Pulse"
#define X_94 "Sangonomiya Kokomi"
#define X_95 "Kujo Sara"
#define X_96 "Raiden Shogun"
#define X_97 "Engulfing Lightning"
#define X_98 "Everlasting Moonglow"
#define X_99 "Yae Miko"
#define X_100 "Thoma"
#define X_101 "Polar Star"
#define X_102 "Mouun's Moon"
#define X_103 "Wavebreaker's Fin"
#define X_104 "Akuoumaru"
#define X_105 "Arataki Itto"
#define X_106 "Gorou"
#define X_107 "Redhorn Stonethresher"
#define X_108 "Yun Jin"
#define X_109 "Shenhe"
#define X_110 "Calamity Queller"
#define X_111 "Kamisato Ayato (Hydro)"
#define E_1 "Unexpected kind! Error code: 1"
#define E_2 "Unexpected fate_weapon! Error code: 2"
#define E_3 "Unexpected resultt! Error code: 3"
#define E_4 "Unexpected resultu! Error code: 4"
#define E_5 "Unexpected chosen_event! Error code: 5"
#define E_6 "Unexpected quit! Error code: 6"
#define E_7 "Unexpected chosen_banner! Error code: 7"
#define E_8 "Unexpected five_count! Error code: 8"
#define E_9 "Unexpected ij! Error code: 9"
#define E_10 "Unexpected d_item_n[kind]! Error code: 10"
#define E_11 "Arguments error! Usage: chosen_banner chosen_event wishes_number"
#define V_1 "Current chosen Banner "
#define V_2 "Current chosen Event "
#define V_3 "Current up-ed 5-star item No. "
#define V_4 "Current state of the print function "
#define V_5 "Current 4-star pity "
#define V_6 "Current 5-star pity "
#define V_7 "Current non-up-4-star pity "
#define V_8 "Current non-up-5-star pity "
#define V_9 "Number of all items "
#define V_10 "Number of all 5-star items "
#define V_11 "Number of all 5-star characters "
#define V_12 "Number of all 5-star weapons "
#define V_13 "Number of all 4-star items "
#define V_14 "Number of all 4-star characters "
#define V_15 "Number of all 4-star weapons "
#define V_16 "If Noelle appears in the first 10 pulls (Novice Wish only)  "
#define V_17 "Sum of all 5-star pities "
#define V_18 "Max of all 5-star pities "
#define V_19 "Min of all 5-star pities "
#define V_20 "The pity unit Max of all 5-star pities happens "
#define V_21 "The pity unit Min of all 5-star pities happens "
#define V_22 "The location Max of all 5-star pities happens "
#define V_23 "The location Min of all 5-star pities happens "
#define V_24 "Current 4-star-character pity "
#define V_25 "Current 4-star-weapon pity "
#define V_26 "Current 5-star-character pity "
#define V_27 "Current 5-star-weapon pity "
#define V_28 "Current weight of 5-star items "
#define V_29 "Current weight of 4-star items "
#define V_30 "Current weight of 3-star items "
#define V_31 "Number of non-up-4-star-characters of this banner "
#define V_32 "Number of non-up-4-star-weapons of this banner "
#define V_33 "If the chosen Banner is changed "
#define V_34 "If the chosen Banner is Dual and changed "
#define V_35 "If the to-be-Dual banner has the supposed Banner type "
#define V_36 "If the to-be-Dual banner has the supposed Event type "
#define V_37 "Epitomized Path chosen weapon (EP banners only)  "
#define V_38 "Epitomized Path fate points (EP banners only)  "
#define V_39 "Luckiness "
#define V_40 "If the loop should be break in S Mode "
#define V_41 "If it's S Mode "
#endif